// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1BSVOyAEaBwYypwB3iyyDewSl80M9OCU',
    appId: '1:1084008894614:web:8fa759cea2f5d932ebf2b7',
    messagingSenderId: '1084008894614',
    projectId: 'fir-practice-d9721',
    authDomain: 'fir-practice-d9721.firebaseapp.com',
    storageBucket: 'fir-practice-d9721.appspot.com',
    measurementId: 'G-2CJ9BV2H2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYLNOVRQCWdUH_GNS8kiRa7LAVJTsz_o',
    appId: '1:1084008894614:android:10cf803cbc23b0e1ebf2b7',
    messagingSenderId: '1084008894614',
    projectId: 'fir-practice-d9721',
    storageBucket: 'fir-practice-d9721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1KE3tzLHp9sxOmgVJzE23vLG5gcHfq8',
    appId: '1:1084008894614:ios:61976ac46af242eaebf2b7',
    messagingSenderId: '1084008894614',
    projectId: 'fir-practice-d9721',
    storageBucket: 'fir-practice-d9721.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1KE3tzLHp9sxOmgVJzE23vLG5gcHfq8',
    appId: '1:1084008894614:ios:61976ac46af242eaebf2b7',
    messagingSenderId: '1084008894614',
    projectId: 'fir-practice-d9721',
    storageBucket: 'fir-practice-d9721.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1BSVOyAEaBwYypwB3iyyDewSl80M9OCU',
    appId: '1:1084008894614:web:9305f82717762f93ebf2b7',
    messagingSenderId: '1084008894614',
    projectId: 'fir-practice-d9721',
    authDomain: 'fir-practice-d9721.firebaseapp.com',
    storageBucket: 'fir-practice-d9721.appspot.com',
    measurementId: 'G-ZMDFS1QSES',
  );

}